Added the smoke tests in the resource folder

diff --git a/.github/workflows/performance-test.yml b/.github/workflows/performance-test.yml
--- a/.github/workflows/performance-test.yml
+++ b/.github/workflows/performance-test.yml
@@ -1,96 +1,102 @@
-name: Sandbox smoke test
+name: Run performance tests
 
 on:
   workflow_dispatch:
     inputs:
-      jdbcJar:
-        description: 'JDBC jar version (e.g: firebolt-jdbc-3.5.1.jar)'
+      database:
+        description: 'Database (staging) - a new one will be created if not provided'
         required: false
-        type: string
-        default: 'firebolt-jdbc-3.6.0.jar'
-      runId:
-        description: 'The run id of the workflow that created the artifact'
-        required: true
-        type: string
+        default: ''
+      threads:
+        description: 'Number of threads/users'
+        required: false
+        default: '5'
+      loops:
+        description: 'Number of iterations for every thread'
+        required: false
+        default: '50'
+
 jobs:
-  run-jdbc-jar:
+  build:
+    uses: ./.github/workflows/build.yml
+  run-performance-test:
     runs-on: ubuntu-latest
-
+    needs: build
     steps:
-      - name: Install java
-        uses: actions/setup-java@v3
+      - name: Check out code
+        uses: actions/checkout@v3
+      - name: Create dependency folder for JMX
+        run: |
+          mkdir dependencies
+      - name: Download uber-jar
+        id: download-jar
+        uses: actions/download-artifact@v4.1.7
         with:
-          distribution: 'zulu'
-          java-version: '11'
+          name: ${{ needs.build.outputs.uber-jar }}
+          path: dependencies
+      - name: Setup database and engine
+        id: setup
+        if: ${{ inputs.database == '' }}
+        uses: firebolt-db/integration-testing-setup@v1
+        with:
+          firebolt-username: ${{ secrets.FIREBOLT_STG_USERNAME }}
+          firebolt-password: ${{ secrets.FIREBOLT_STG_PASSWORD }}
+          api-endpoint: "api.staging.firebolt.io"
+          region: "us-east-1"
+          instance-type: "C2"
+          engine-scale: 2
 
-      # in order to use gh script we need the env variable GH_TOKEN
-      - name: Download jdbc jar from job run
-        env:
-          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      - name: Determine database name
+        id: find-database-name
         run: |
-          echo "🔍 Finding the jdbc jar for version: ${{ inputs.jdbcJar }} in run: ${{ inputs.runId }}"
+          if ! [[ -z "${{ inputs.database }}" ]]; then
+             echo "database_name=${{ inputs.database }}" >> $GITHUB_OUTPUT
+          else
+             echo "database_name=${{ steps.setup.outputs.database_name }}" >> $GITHUB_OUTPUT
+          fi
 
-          # Get artifact ID
-          ARTIFACT_ID=$(gh api repos/firebolt-db/jdbc/actions/runs/${{ inputs.runId }}/artifacts \
-            -q ".artifacts[] | select(.name==\"${{ inputs.jdbcJar }}\") | .id")
-          echo "🎯 Artifact ID: $ARTIFACT_ID"
-
-          # Download the artifact
-          mkdir -p artifact
-          gh api --method GET \
-            -H "Accept: application/vnd.github+json" \
-            -H "Authorization: token $GH_TOKEN" \
-            -H "X-GitHub-Api-Version: 2022-11-28" \
-            /repos/firebolt-db/jdbc/actions/artifacts/$ARTIFACT_ID/zip \
-            > artifact/artifact.zip
-
-          echo "📂 Extracting..."
-          unzip artifact/artifact.zip -d artifact/
-          
-          echo "Current directory is: $(pwd)"
-          ls -la
-          ls -al artifact/
-
-      - name: Create java file
+      - name: Run JMeter Tests
+        uses: rbhadti94/apache-jmeter-action@v0.5.0
+        with:
+          testFilePath: JDBC.jmx
+          dependencyFolder: dependencies
+          outputReportsFolder: reports/
+          args: -Jdatabase=${{ steps.find-database-name.outputs.database_name }} -Jpassword=${{ secrets.SERVICE_ACCOUNT_SECRET_STAGING }} -Jusername=${{ secrets.SERVICE_ACCOUNT_ID_STAGING }} -Jdriver=${{ needs.build.outputs.uber-jar }} -Jenvironment=staging -Jthreads=${{ inputs.threads }} -Jloops=${{ inputs.loops }}
+      - name: Upload JMeter report
+        uses: actions/upload-artifact@v4
+        with:
+          name: performance_test_report
+          path: reports
+      - name: Upload JMeter logs
+        uses: actions/upload-artifact@v4
+        with:
+          name: jmeter_log.log
+          path: jmeter_log.log
+      - name: Get short commit SHA
+        id: short-sha
+        run: echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
+      - name: Extract test summary
+        id: summary
         run: |
-          cat <<EOF > SmokeTest.java          
-          import com.firebolt.FireboltDriver;
-          import com.firebolt.jdbc.connection.LocalhostFireboltConnection;
-          import java.sql.Connection;
-          import java.sql.SQLException;
-          import java.util.Properties;
-          
-          public class SmokeTest {
-          
-            public static void main(String[] args) {
-              FireboltDriver fireboltDriver = new FireboltDriver();
-              String url = createUrlConnectionString("goprean", "goprean");
-              System.out.println("Connecting to localhost " + url);
-              try (Connection connection = fireboltDriver.connect(url, new Properties())) {
-                LocalhostFireboltConnection localhostFireboltConnection = connection.unwrap(LocalhostFireboltConnection.class);
-          
-                System.out.println("Successfully connected to localhost");
-              } catch (SQLException e) {
-                 e.printStackTrace();
-                 throw new RuntimeException(e);
-              }
-            }
-          
-            private static String createUrlConnectionString(String database, String engine) {
-              StringBuilder urlConnectionBuilder = new StringBuilder("jdbc:firebolt:")
-                  .append(database)
-                  .append("?engine=").append(engine)
-                  .append("&account=developer")
-                  .append("&host=localhost")
-                  .append("&access_token=some_token");
-              return urlConnectionBuilder.toString();
-            }
-          
-          }
-          EOF
-
-      - name: Compile class
-        run: javac -cp artifact/${{ inputs.jdbcJar }} SmokeTest.java
-
-      - name: Run class
-        run: java -cp artifact/${{ inputs.jdbcJar }}:. SmokeTest
+          result="$(date +"%d-%m-%y %T %Z"),${{ inputs.threads }},$(jq -r '.Total.sampleCount, .Total.errorCount, .Total.errorPct, .Total.meanResTime, .Total.medianResTime, .Total.minResTime, .Total.maxResTime, .Total.pct1ResTime, .Total.pct2ResTime, .Total.pct3ResTime, .Total.throughput | round' reports/statistics.json| tr '\n' '|' | sed 's/|$/\n/'),${{ steps.short-sha.outputs.short_sha }},$GITHUB_REF"
+          echo "SUMMARY=$(echo "$result" | tr '|' ',')" >> $GITHUB_OUTPUT
+          sudo rm -rf "/home/runner/work/jdbc/jdbc/reports"
+      - name: Checkout history branch
+        uses: actions/checkout@v3
+        with:
+          ref: performance-tests-history
+      - name: Append history with test summary
+        run: |
+          echo "${{ steps.summary.outputs.summary }}" >> results.csv
+      - name: push
+        uses: stefanzweifel/git-auto-commit-action@v4
+        with:
+          commit_message: Push history
+          branch: performance-tests-history
+      - name: Publish results
+        run: |
+          chmod u+x export_performance_tests_results.sh
+          echo "### :rocket: Tests Results :rocket:" >> $GITHUB_STEP_SUMMARY
+          echo "| Date  | Thread count  | Sample count  | Error count | Error % | Mean response time |Median response time | Min response time | Max response time | 1st percentile response time | 2nd percentile response time | 3nd percentile response time | Throughput | Commit | Branch" >> $GITHUB_STEP_SUMMARY
+          echo "| -------------  | -------------  | -------------  | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |" >> $GITHUB_STEP_SUMMARY
+          ./export_performance_tests_results.sh
